### ISSUE TITLE
Documentation visualization

### ISSUE THREAD

**Issue by fulldecent** [cggaurav/juicydrop#1]
I just want to clarify, are these the original WinAmp visualizations? And if, so could you please mention which version they are from?

Also, I recall that WinAmp supported visualization plugins. Are you familiar with this? And do know about how this process work and how I might implement that?

I love the old WinAmp and since 2000 have not seen an app that understands party visualizations like they did.

I am thinking to work on this project to allow input from the microphone like this has http://preziotte.com/partymode/ Naturally the only point here would be to take advantage of the visualization.

**Comment by cggaurav** [comment]
Hey William,

Yeah, these are the original visualizations though they are recreated using
HTML5. There is a visualization file where you can tweak the parameters and
the rendering - from what I remember.

I am not on this actively - but feel free to fork or PR.

**Comment by fulldecent** [comment]
Thank you for clarifying.
